Grabbing the Streamflow Data

In [1]:
from pynhd import NLDI, WaterData, NHDPlusHR, GeoConnex
import geopandas as gpd
import pandas as pd
from supporting_scripts import getData, SNOTEL_Analyzer, dataprocessing, mapping
from shapely.geometry import box, Polygon
import os
import datetime
import matplotlib.pyplot as plt
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [2]:
nldi = NLDI()
usgs_gage_id = "09010500" # NWIS id for Colorado River below Baker Gulch

In [11]:
import importlib
importlib.reload(getData)

In [7]:
#get streamflow information using the NWIS id for the gage and ghte get_usgs_streamflow function in getData.py 
streamflow = getData.get_usgs_streamflow(usgs_gage_id)

Retrieving data for Site: 09010500 from 1980-01-01 to 2026-03-30...

In [8]:
streamflow.head()

                            site_no  00060_Mean 00060_Mean_cd
datetime
1980-01-01 00:00:00+00:00  09010500         8.0             A
1980-01-02 00:00:00+00:00  09010500         8.0             A
1980-01-03 00:00:00+00:00  09010500         8.0             A
1980-01-04 00:00:00+00:00  09010500         8.0             A
1980-01-05 00:00:00+00:00  09010500         8.0             A

In [9]:
streamflow.tail()

                            site_no  00060_Mean 00060_Mean_cd
datetime
2026-03-25 00:00:00+00:00  09010500   -999999.0        P, Ice
2026-03-26 00:00:00+00:00  09010500   -999999.0        P, Ice
2026-03-27 00:00:00+00:00  09010500       110.0             P
2026-03-28 00:00:00+00:00  09010500        88.4             P
2026-03-29 00:00:00+00:00  09010500        89.8             P

In [19]:
import importlib
importlib.reload(dataprocessing)

In [20]:
cleaned = dataprocessing.clean_nwis_dataframe(streamflow)
#set the index name to Date
cleaned.index.name = "Date"
cleaned.tail()

             site_no  flow_cms
Date
2026-03-25  09010500       NaN
2026-03-26  09010500       NaN
2026-03-27  09010500  3.114848
2026-03-28  09010500  2.503205
2026-03-29  09010500  2.542849

In [21]:
#save the cleaned dataframe to a csv file
# Use the getData module to retrieve data 
OutputFolder = 'files/NWIS'
if not os.path.exists(OutputFolder):
    os.makedirs(OutputFolder)
cleaned.to_csv(f'{OutputFolder}/streamflow_{usgs_gage_id}.csv')